version: "3"

services:
  mariadb:
    image: mariadb:10.6.14
    container_name: mariadb
    restart: always
    env_file: mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8787:8080"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: minio server --address ':9000' --console-address ':9001' /data
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - /var/minio:/data
    env_file: minio.env
